apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: prometheus-example-app
  name: prometheus-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-example-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-example-app
    spec:
      containers:
      - name: prometheus-example-app
        image: public.ecr.aws/a9q6d6e8/prometheus-example-app:0.4.0
        ports:
        - name: web
          containerPort: 8080
        env:
        - name: LOGZER_NAME
          value: Simon
        - name: LOGZER_TENURE_IN_DAYS
          value: "246"
