apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      external_labels:
        p8s_logzio_name: prometheus-example
    remote_write:
      - url: https://listener.logz.io:8053
        bearer_token: <LOGZIO-METRICS-TOKEN>
        remote_timeout: 30s
        queue_config:
          batch_send_deadline: 5s 
          max_shards: 10 
          min_shards: 1
          max_samples_per_send: 500 
          capacity: 10000
    scrape_configs:
      - job_name: kubernetes-service-endpoints
        kubernetes_sd_configs:
          - role: endpoints