apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: prometheus
  name: prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
  type: NodePort